### ISSUE TITLE
Ch 6: Security Exception when adding new entry on Android

### ISSUE THREAD

**Issue by jc184** [PacktPublishing/Mastering-Xamarin.Forms-Second-Edition#7]
I'm using Android 8.1 Oreo / API 27, and I'm having some problems with my code. I'm getting the above error which is obviously to do with gps location permissions when requesting the new location. I've set the necessary permissions in my **AndroidManifest.xml** file, but I haven't been able to code a solution for _requesting_ the permissions, despite going through the first 5 chapters faithfully. I'm not sure why I'm getting this error as I could add new entries in my own TripLog application by chapter 3. 
Could you advise me whether I need to add request permissions to my code, or whether there is a simple solution later in the book. Perhaps I've missed something but I can't see permissions mentioned anywhere in an otherwise enjoyable book

**Comment by edsnider** [comment]
You need to request permission at runtime on API >= 23. This isn't covered in the book, but here is a Xamarin blog post that explains it all for you: https://devblogs.microsoft.com/xamarin/requesting-runtime-permissions-in-android-marshmallow/
